export const LANGUAGES = [
    { label: 'English', value: 'EN' },
    { label: 'Hindi', value: 'HI' },
    { label: 'Bengali', value: 'BN' },
    { label: 'Telugu', value: 'TE' },
    { label: 'Marathi', value: 'MR' },
    { label: 'Kannada', value: 'KN' },
    { label: 'Gujarati', value: 'GU' },
    { label: 'Malayalam', value: 'ML' },
    { label: 'Tamil', value: 'TA' },
  ];
  export const GENRES = [
    { label: 'Action', value: 'ACTION' },
    { label: 'Adventure', value: 'ADVENTURE' },
    { label: 'Animation', value: 'ANIMATION' },
    { label: 'Comedy', value: 'COMEDY' },
    { label: 'Crime', value: 'CRIME' },
    { label: 'Drama', value: 'DRAMA' },
    { label: 'Fantasy', value: 'FANTASY' },
    { label: 'Historical', value: 'HISTORICAL' },
    { label: 'Horror', value: 'HORROR' },
    { label: 'Musical', value: 'MUSICAL' },
    { label: 'Mystery', value: 'MYSTERY' },
    { label: 'Romance', value: 'ROMANCE' },
    { label: 'Science Fiction', value: 'SCI_FI' },
    { label: 'Thriller', value: 'THRILLER' },
    { label: 'War', value: 'WAR' },
    { label: 'Western', value: 'WESTERN' },
  ];
  